import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { ArrowUpRight, ArrowRight, ArrowDown, Menu, X, Cpu, ShieldCheck, Sparkles, Globe2, Layers3, BookOpen, MapPin } from 'lucide-react';
import { articles, projects } from './content';
import './styles.css';

function App() {
  const [menu, setMenu] = useState(false);
  const [filter, setFilter] = useState('Todas');
  useEffect(() => {
    const observer = new IntersectionObserver(entries => entries.forEach(entry => { if (entry.isIntersecting) { entry.target.classList.add('visible'); observer.unobserve(entry.target); } }), { threshold: .08 });
    document.querySelectorAll('.reveal').forEach(el => observer.observe(el));
    return () => observer.disconnect();
  }, []);
  const filtered = filter === 'Todas' ? articles : articles.filter(a => a.category === filter);
  return <>
    <a className="skip-link" href="#contenido">Saltar al contenido</a>
    <div className="topbar"><span>Dirección de Modernización</span><span><MapPin size={12}/> Tinogasta, Catamarca, Argentina</span></div>
    <header><a href="#" className="brand" aria-label="Innova Tinogasta, inicio"><img src="/brand/ICONO2.png" alt=""/><img src="/brand/LETRA.png" alt="Innova Tinogasta"/></a><nav aria-label="Navegación principal" className={menu ? 'open' : ''}><a href="#inicio" onClick={() => setMenu(false)}>Inicio</a><a href="#novedades" onClick={() => setMenu(false)}>Novedades</a><a href="#proyectos" onClick={() => setMenu(false)}>Proyectos</a><a href="#nosotros" onClick={() => setMenu(false)}>Nosotros</a></nav><a className="nav-cta" href="#proyectos">Explorá la innovación <ArrowUpRight size={17}/></a><button className="menu-toggle" aria-label={menu ? 'Cerrar menú' : 'Abrir menú'} aria-expanded={menu} onClick={() => setMenu(!menu)}>{menu ? <X/> : <Menu/>}</button></header>
    <main id="contenido">
      <section className="hero" id="inicio"><div className="hero-copy"><span className="eyebrow"><i/> IDEAS LOCALES. POSIBILIDADES INFINITAS.</span><h1>El futuro se<br/>construye <em>acá.</em><span className="title-dot"/></h1><p>Conectamos tecnología, ideas y personas para impulsar una Tinogasta más innovadora.</p><div className="hero-actions"><a className="button primary" href="#proyectos">Conocé los proyectos <ArrowUpRight size={19}/></a><a className="text-link" href="#novedades">Qué hay de nuevo <ArrowRight size={18}/></a></div><div className="hero-foot"><span className="little-cross">✳</span><span>Una ciudad con identidad.<br/><strong>Una comunidad mirando hacia adelante.</strong></span></div></div><div className="hero-art" aria-label="Identidad de Innova Tinogasta"><div className="art-grid"/><div className="orbit orbit-one"/><div className="orbit orbit-two"/><div className="orbit orbit-three"/><span className="art-coordinate">27°04′ S / 67°34′ O</span><div className="eagle-disc"><img src="/brand/ICONO.png" alt="Cóndor de Innova Tinogasta"/></div><div className="floating-tag tag-top"><span className="tag-icon"><Cpu size={19}/></span>Innovación con identidad</div><div className="floating-tag tag-bottom"><span className="live-dot"/>El próximo paso es nuestro <ArrowUpRight size={17}/></div><span className="pixel p1"/><span className="pixel p2"/><span className="pixel p3"/><div className="art-caption"><span>DESDE TINOGASTA</span><span>HACIA LO QUE VIENE ↗</span></div></div></section>
      <div className="topic-strip"><span>EL CAMBIO EMPIEZA CON UNA IDEA</span><div><Sparkles/> Innovación</div><b>+</b><div><Globe2/> Comunidad</div><b>+</b><div><Cpu/> Tecnología</div><b>+</b><div><BookOpen/> Conocimiento</div><a href="#novedades" aria-label="Ir a novedades"><ArrowDown size={19}/></a></div>
      <section id="novedades" className="section news"><div className="section-heading reveal"><div><span className="eyebrow">01 / CONECTADOS CON LO QUE VIENE</span><h2>Ideas que nos <em>mueven.</em></h2></div><p>Tecnología en palabras simples.<br/>Noticias y lecturas para seguir aprendiendo.</p></div><div className="filters" aria-label="Filtrar novedades">{['Todas','Inteligencia artificial','Ciudadanía digital','Educación'].map(f => <button key={f} aria-pressed={filter === f} className={filter === f ? 'active' : ''} onClick={() => setFilter(f)}>{f}{f === 'Todas' && <span>03</span>}</button>)}</div><div className="news-grid">{filtered.map(article => <a className={'news-card '+article.visual} key={article.id} href={article.url} target="_blank" rel="noopener noreferrer"><div className="news-visual"><span className="visual-label">INNOVA / EXPLORA</span>{article.visual === 'ai' ? <div className="ai-sculpture"><span/><span/><span/><span/><span/></div> : article.visual === 'security' ? <ShieldCheck className="large-icon" strokeWidth={.8}/> : <div className="education-art"><span>a</span><span>i</span><Sparkles/></div>}<span className="visual-bottom">{article.label}<ArrowUpRight size={20}/></span></div><div className="news-content"><span className="category">{article.category}</span><h3>{article.title}</h3><p>{article.description}</p><div className="article-source">{article.source}<ArrowUpRight size={17}/></div></div></a>)}</div><p className="source-note">Selección de lecturas de fuentes externas. Cada nota abre su publicación original.</p></section>
      <section id="proyectos" className="projects-section"><div className="section-heading reveal"><div><span className="eyebrow">02 / DE LAS IDEAS A LA ACCIÓN</span><h2>Innovación que<br/>se vuelve <em>real.</em></h2></div><p>Un espacio para conocer los proyectos<br/>de la Dirección de Modernización.</p></div>{projects.length ? <div className="project-list">{projects.map(project => <article key={project.id}><span className="eyebrow">{project.category} / {project.status}</span><h3>{project.title}</h3><p>{project.description}</p>{project.url && <a className="text-link" href={project.url} target="_blank" rel="noopener noreferrer">Conocer proyecto <ArrowUpRight size={18}/></a>}</article>)}</div> : <div className="project-placeholder reveal"><div className="project-art"><Layers3 size={88} strokeWidth={.7}/><span className="project-art-cross">+</span></div><div><span className="small-label">PORTAFOLIO DE PROYECTOS</span><h3>Lo que hacemos,<br/>en un solo lugar.</h3><p>Próximamente vas a encontrar los proyectos realizados, sus objetivos y su aporte a la comunidad de Tinogasta.</p><span className="soon"><span/> Próximamente</span></div><span className="project-number" aria-hidden="true">↗</span></div>}</section>
      <section className="about section reveal" id="nosotros"><div className="about-symbol"><img src="/brand/LOGO.png" alt="Innova Tinogasta"/></div><div className="about-copy"><span className="eyebrow">03 / TECNOLOGÍA CON PROPÓSITO</span><h2>El centro de la<br/>innovación sos <em>vos.</em></h2><p>Innova Tinogasta es el espacio de la Dirección de Modernización para acercar la tecnología a nuestra comunidad y compartir los proyectos que realizamos.</p><p>Creemos en el conocimiento compartido, las ideas que nacen acá y una transformación que nos incluya a todos.</p><a href="#novedades" className="text-link">Descubrí, aprendé y conectá <ArrowUpRight size={19}/></a></div></section>
      <section className="closing"><span className="eyebrow">EL FUTURO ES UN TRABAJO EN EQUIPO</span><h2>De Tinogasta.<br/><span>Para lo que viene.</span><ArrowUpRight aria-hidden="true"/></h2><a href="#inicio" className="button light">Sigamos conectados <ArrowUpRight size={18}/></a><div className="closing-pixels" aria-hidden="true"><i/><i/><i/><i/></div></section>
    </main><footer><a className="brand" href="#inicio"><img src="/brand/LETRA.png" alt="Innova Tinogasta"/></a><p>Dirección de Modernización<br/>Tinogasta, Catamarca.</p><span>© {new Date().getFullYear()} Innova Tinogasta</span><a href="#inicio" className="back-top" aria-label="Volver al inicio">↑</a></footer>
  </>;
}

createRoot(document.getElementById('root')).render(<App/>);
